source "https://rubygems.org"
ruby "~> 3.2"
gem "rails", "~> 7.1.5"
gem "pg", "~> 1.5"
gem "puma", ">= 5.0"
gem "sidekiq", "~> 7.3"
gem "sidekiq-cron", "~> 1.12"
gem "redis", ">= 5"
gem "faker"
gem "ruby-openai"
gem "cssbundling-rails"
gem "jsbundling-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "kaminari"
gem "bcrypt", "~> 3.1.7"
group :development, :test do
  gem "rspec-rails"
  gem "factory_bot_rails"
end
gem "bootsnap", require: false
gem "sprockets-rails"
